In [2]:
import numpy as np
import matplotlib.pyplot as plt 
from copy import deepcopy, copy

# Zadanie 1 - Gauss-Jordan

In [157]:
# it destroys A matrix making it identity matrix
# result after invoking the function is in array B
# pivoting function returns numbers of swapped columns if there was a change
def gauss_jordan(A, B, pivoting):
    perm = [i for i in range(len(A))]
    for i in range(len(A[0])):
        c1, c2 = pivoting(A, B, i)
        perm[c1], perm[c2] = perm[c2], perm[c1]
        # counting
        for j in range(len(A)):
            if j != i: 
                d = -A[j][i]/A[i][i]
                for k in range(i, len(A[i])):
                    A[j][k] += d*A[i][k]
                B[j] += d*B[i]
        d = A[i][i]
        for k in range(i, len(A[0])):
            A[i][k] /= d
        B[i] /= d
    #restore order
    res = [0 for i in range(len(perm))]
    for i in range(len(perm)):
        res[perm[i]] = B[i]
    B[:] = res[:]

In [158]:
A = np.random.rand(10,10)
B = np.random.rand(10)

## Bez pivotingu

In [159]:
def no_pivoting(A, B, i):
    return i,i

In [160]:
An = deepcopy(A)
Bn = copy(B)
gauss_jordan(An, Bn, pivoting=no_pivoting)
print(An)
print((A @ Bn) - B)

[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  8.88178420e-16  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00  0.00000000e+00
   0.00000000e+00 -5.55111512e-17  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -4.44089210e-16 -1.11022302e-16  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-1.11022302e-16  0.00000000e+00  0.00000000e+00  0.00000000e+00
   1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   1.38777878e-17  1.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00

## Partial pivoting

In [161]:
def swap_rows(A, B, i, j):
    A[[i,j]] = A[[j,i]]
    B[i], B[j] = B[j], B[i]
def swap_columns(A, B, i, j):
    A[:, [j,i]] = A[:, [i,j]]

In [162]:
def partial_pivoting(A, B, i):
    besti = i
    for j in range(i+1,len(A)):
        if A[besti][i] < A[j][i]:
            besti = j
    swap_rows(A, B, i, besti)
    return i, i

In [163]:
Ap = deepcopy(A)
Bp = copy(B)
gauss_jordan(Ap, Bp, pivoting=partial_pivoting)
print(Ap)
print(A @ Bp - B)

[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   4.44089210e-16  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00 -1.11022302e-16
  -2.22044605e-16  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  1.00000000e+00 -1.42108547e-14  0.00000000e+00
   0.00000000e+00  0.00000000e+00

## Full pivoting

In [164]:
def full_pivoting(A, B, i):
    bestj = i
    bestk = i
    for j in range(i,len(A)):
        for k in range(i, len(A[j])):
            if abs(A[bestj][bestk]) < abs(A[j][k]):
                bestj = j
                bestk = k
    swap_rows(A, B, i, bestj)
    swap_columns(A, B, i, bestk)
    return i, bestk

In [165]:
Af = deepcopy(A) #np.array([[1.,-4.,4.,7.], [0.,2.,-1.,0.], [2.,1.,1.,4.], [2.,-3.,2.,-5.]]) #deepcopy(A)
Bf = copy(B) #np.array([4.,5.,2.,9.])#copy(B)
gauss_jordan(Af, Bf, pivoting=full_pivoting)
print(Af)
print(A @ Bf - B)

[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -6.93889390e-18  0.00000000e+00
   1.00000000e+00 -1.11022302e-16  0.00000000e+00  0.00000000e+00
   0.00000000e+00 -1.11022302e-16]
 [ 0.00000000e+00  0.00000000e+00 -2.77555756e-17  0.00000000e+00
   0.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00

# Zadanie 2

In [166]:
def LU(A):
    for i in range(len(A[0])):
        #counting
        for j in range(i+1, len(A)):
            d = -A[j][i]/A[i][i]
            for k in range(i, len(A[i])):
                A[j][k] += d*A[i][k]
            A[j][i] = -d;
    L = np.zeros((len(A), len(A)))
    U = np.zeros((len(A), len(A)))
    for i in range(len(A[0])):
        for j in range(len(A)):
            if i==j:
                L[i][j] = 1
                U[i][j] = A[i][j]
            elif i < j:
                L[i][j] = 0
                U[i][j] = A[i][j]
            else:
                L[i][j] = A[i][j]
                U[i][j] = 0
    return L, U
                

In [167]:
A = np.random.rand(5,5)
print(A)
L, U = LU(A)
print(L)
print(U)
print(L @ U)

[[0.64275299 0.12707073 0.55244162 0.81936155 0.40637603]
 [0.3056825  0.47356862 0.50373971 0.38573764 0.07884334]
 [0.31366425 0.49212522 0.22730424 0.73364256 0.52310415]
 [0.77509804 0.79146898 0.03391828 0.66239704 0.74270854]
 [0.62667144 0.97898752 0.94739527 0.01640377 0.66754117]]
[[1.         0.         0.         0.         0.        ]
 [0.47558315 1.         0.         0.         0.        ]
 [0.48800123 1.04109693 1.         0.         0.        ]
 [1.20590343 1.54485221 3.42630622 1.         0.        ]
 [0.9749802  2.06976935 0.30714449 0.59438369 1.        ]]
[[ 0.64275299  0.12707073  0.55244162  0.81936155  0.40637603]
 [ 0.          0.41313592  0.24100778 -0.00393691 -0.11442225]
 [ 0.          0.         -0.29320041  0.33789183  0.44391681]
 [ 0.          0.          0.         -1.47731279 -1.09157115]
 [ 0.          0.          0.          0.          1.02062575]]
[[0.64275299 0.12707073 0.55244162 0.81936155 0.40637603]
 [0.3056825  0.47356862 0.50373971 0.3857376

# Zadanie 3