In [71]:
import numpy as np
from scipy import linalg
from copy import deepcopy

## Zad 1

In [145]:
def qr(A):
    Q = np.zeros(A.shape)
    for i in range(len(A[0])):
        ai = A[:,i]
        ui = A[:,i]
        for j in range(i):
            ui -= np.dot(Q[:,j],ai)*Q[:,j]
        ui = ui/np.linalg.norm(ui)
        Q[:,i] = ui[:]
    
    R = np.zeros(A.shape)
    for i in range(len(A)):
        for j in range(i,len(A[0])):
            R[i][j] = np.dot(Q[:,i],A[:,j])
    return Q, R

In [146]:
A = np.random.random((3,3))
# A = np.array([[0.08223871, 0.85877601, 0.24677757],
#  [0.01876868, 0.98501504, 0.22333477],
# [0.76955748, 0.16823208, 0.83330313]])

print(qr(A)[0])
print(np.linalg.qr(A)[0])
Q, R = qr(A)
print(A, Q@R)

[[ 0.07919006  0.96817727 -0.23740622]
 [ 0.99260851 -0.09855405 -0.07081983]
 [ 0.09196349  0.23004321  0.9688255 ]]
[[-0.07919006  0.96817727 -0.23740622]
 [-0.99260851 -0.09855405 -0.07081983]
 [-0.09196349  0.23004321  0.9688255 ]]
[[ 0.07175262  0.89011497 -0.0293653 ]
 [ 0.89938383 -0.09060782 -0.00875986]
 [ 0.08332638  0.21149526  0.11983618]] [[ 0.07175262  0.89011497 -0.0293653 ]
 [ 0.89938383 -0.09060782 -0.00875986]
 [ 0.08332638  0.21149526  0.11983618]]


## Zad 2

In [155]:
def solve(A, b):
    Q, R = qr(A)
    b = Q.T@b
    return np.linalg.solve(R[:len(A[0])], b)

In [156]:
xs = np.array([i for i in range(-5, 6)], dtype=np.float64)
ys = np.array([2,7,9,12,13,14,14,13,10, 8, 4], dtype=np.float64)
A = np.array([[1, x, x*x] for x in xs], dtype=np.float64)
print(solve(A, ys))
print(np.linalg.lstsq(A, ys))

[ 9.63636364  0.18181818 -0.43356643]
(array([ 9.63636364,  0.18181818, -0.43356643]), array([1.62237762]), 3, array([29.29163703, 10.48808848,  3.31662479]))


/home/arkadius/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """


## Zad 1.2

In [165]:
def cond(A):
    e = np.linalg.eig(A)
    return np.real(e[0][0])/np.real(e[0][1])

res = []
for i in range(80):    
    A = np.random.random((3,3))
    Q, R = qr(A)
    res.append((cond(A), np. 

-4.175352959750549
